server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true